// Tabu kelime havuzu. Her kelimenin "Zor" modda kullanılacak 7 yasaklı kelimesi vardır.
// Kolay modda ilk 3'ü, Orta modda ilk 5'i, Zor modda 7'sinin tamamı gösterilir.
// NOT: Bu liste 1000 kelimeye ulaşana kadar parça parça büyütülüyor. Şu an: 300/1000.
window.WORDS_POOL = [
  { id: 1, word: "Masa", forbidden: ["Sandalye", "Yemek", "Ayak", "Üstü", "Ahşap", "Oturmak", "Salon"] },
  { id: 2, word: "Sandalye", forbidden: ["Masa", "Oturmak", "Ayak", "Sırt", "Mobilya", "Salon", "Ahşap"] },
  { id: 3, word: "Yatak", forbidden: ["Uyumak", "Yorgan", "Yastık", "Oda", "Çarşaf", "Uyku", "Baza"] },
  { id: 4, word: "Dolap", forbidden: ["Kıyafet", "Raf", "Kapak", "Oda", "Askı", "Çekmece", "Ahşap"] },
  { id: 5, word: "Ayna", forbidden: ["Yansıma", "Görüntü", "Cam", "Duvar", "Yüz", "Bakmak", "Çerçeve"] },
  { id: 6, word: "Perde", forbidden: ["Pencere", "Kumaş", "Oda", "Örtmek", "Işık", "Salon", "Asmak"] },
  { id: 7, word: "Halı", forbidden: ["Zemin", "Salon", "Desen", "Yün", "Süpürmek", "Yumuşak", "Oda"] },
  { id: 8, word: "Lamba", forbidden: ["Işık", "Ampul", "Aydınlatmak", "Elektrik", "Masa", "Oda", "Karanlık"] },
  { id: 9, word: "Saat", forbidden: ["Zaman", "Kadran", "Akrep", "Yelkovan", "Kol", "Dakika", "Duvar"] },
  { id: 10, word: "Süpürge", forbidden: ["Temizlik", "Toz", "Zemin", "Sap", "Ev", "Süpürmek", "Çöp"] },
  { id: 11, word: "Ütü", forbidden: ["Kıyafet", "Kumaş", "Buhar", "Sıcak", "Düzeltmek", "Kırışık", "Elektrik"] },
  { id: 12, word: "Çamaşır Makinesi", forbidden: ["Kıyafet", "Deterjan", "Yıkamak", "Elektrik", "Su", "Kir", "Program"] },
  { id: 13, word: "Buzdolabı", forbidden: ["Soğuk", "Yiyecek", "Mutfak", "Elektrik", "Kapı", "Saklamak", "Dondurucu"] },
  { id: 14, word: "Fırın", forbidden: ["Pişirmek", "Sıcak", "Mutfak", "Ekmek", "Kek", "Isı", "Kapak"] },
  { id: 15, word: "Tencere", forbidden: ["Yemek", "Kapak", "Mutfak", "Kaynatmak", "Sap", "Ocak", "Çorba"] },
  { id: 16, word: "Tava", forbidden: ["Yağ", "Yumurta", "Sap", "Kızartmak", "Mutfak", "Ocak", "Yemek"] },
  { id: 17, word: "Bıçak", forbidden: ["Kesmek", "Keskin", "Mutfak", "Sap", "Bilemek", "Tehlikeli", "Ekmek"] },
  { id: 18, word: "Çatal", forbidden: ["Yemek", "Sofra", "Diş", "Kaşık", "Masa", "Delmek", "Metal"] },
  { id: 19, word: "Kaşık", forbidden: ["Yemek", "Çorba", "Sofra", "Metal", "Karıştırmak", "Tatlı", "Masa"] },
  { id: 20, word: "Tabak", forbidden: ["Yemek", "Sofra", "Servis", "Cam", "Kırılmak", "Masa", "Yuvarlak"] },
  { id: 21, word: "Bardak", forbidden: ["İçmek", "Su", "Cam", "Sofra", "Kırılmak", "Masa", "Doldurmak"] },
  { id: 22, word: "Termos", forbidden: ["Sıcak", "Çay", "Kapak", "Saklamak", "Metal", "Kahve", "Taşımak"] },
  { id: 23, word: "Mum", forbidden: ["Işık", "Yanmak", "Fitil", "Karanlık", "Doğum Günü", "Erimek", "Alev"] },
  { id: 24, word: "Çöp Kutusu", forbidden: ["Atık", "Poşet", "Kapak", "Mutfak", "Koku", "Atmak", "Geri Dönüşüm"] },
  { id: 25, word: "Anahtar", forbidden: ["Kilit", "Kapı", "Metal", "Açmak", "Cep", "Ev", "Kayıp"] },
  { id: 26, word: "Ekmek", forbidden: ["Fırın", "Un", "Dilim", "Tost", "Buğday", "Somun", "Yemek"] },
  { id: 27, word: "Peynir", forbidden: ["Süt", "Dilim", "Beyaz", "Kaşar", "Kahvaltı", "Ekmek", "Sarı"] },
  { id: 28, word: "Zeytin", forbidden: ["Yağ", "Siyah", "Yeşil", "Kahvaltı", "Ağaç", "Tuzlu", "Ege"] },
  { id: 29, word: "Yumurta", forbidden: ["Tavuk", "Kabuk", "Sarısı", "Beyaz", "Haşlamak", "Kahvaltı", "Omlet"] },
  { id: 30, word: "Süt", forbidden: ["İnek", "Beyaz", "İçmek", "Kahvaltı", "Bardak", "Kalsiyum", "Peynir"] },
  { id: 31, word: "Tereyağı", forbidden: ["Süt", "Ekmek", "Sarı", "Kahvaltı", "Sürmek", "Yağ", "Tost"] },
  { id: 32, word: "Reçel", forbidden: ["Meyve", "Şeker", "Kavanoz", "Kahvaltı", "Ekmek", "Sürmek", "Tatlı"] },
  { id: 33, word: "Bal", forbidden: ["Arı", "Tatlı", "Kavanoz", "Kahvaltı", "Sarı", "Petek", "Şifa"] },
  { id: 34, word: "Şeker", forbidden: ["Tatlı", "Beyaz", "Çay", "Kahve", "Küp", "Diş", "Fabrika"] },
  { id: 35, word: "Tuz", forbidden: ["Tuzlu", "Beyaz", "Yemek", "Deniz", "Baharat", "Sofra", "Kristal"] },
  { id: 36, word: "Biber", forbidden: ["Acı", "Yeşil", "Kırmızı", "Baharat", "Toz", "Sebze", "Dolma"] },
  { id: 37, word: "Domates", forbidden: ["Kırmızı", "Salata", "Sebze", "Sos", "Çorba", "Bahçe", "Sulu"] },
  { id: 38, word: "Patates", forbidden: ["Kızartma", "Sebze", "Toprak", "Püre", "Çorba", "Sarı", "Kabuk"] },
  { id: 39, word: "Soğan", forbidden: ["Ağlamak", "Sebze", "Sos", "Kokusu", "Kabuk", "Mutfak", "Salata"] },
  { id: 40, word: "Sarımsak", forbidden: ["Diş", "Koku", "Baharat", "Sebze", "Sos", "Salata", "Şifa"] },
  { id: 41, word: "Elma", forbidden: ["Meyve", "Kırmızı", "Ağaç", "Sepet", "Kabuk", "Sap", "Tatlı"] },
  { id: 42, word: "Muz", forbidden: ["Meyve", "Sarı", "Kabuk", "Soymak", "Maymun", "Tatlı", "Potasyum"] },
  { id: 43, word: "Portakal", forbidden: ["Meyve", "Turuncu", "Kabuk", "Su", "Vitamin", "Dilim", "Ağaç"] },
  { id: 44, word: "Karpuz", forbidden: ["Meyve", "Yaz", "Kırmızı", "Çekirdek", "Kabuk", "Sulu", "Büyük"] },
  { id: 45, word: "Çilek", forbidden: ["Meyve", "Kırmızı", "Küçük", "Reçel", "Tatlı", "Bahçe", "Sap"] },
  { id: 46, word: "Üzüm", forbidden: ["Meyve", "Salkım", "Bağ", "Şarap", "Kuru", "Tane", "Yeşil"] },
  { id: 47, word: "Kavun", forbidden: ["Meyve", "Sarı", "Yaz", "Sulu", "Kabuk", "Tatlı", "Büyük"] },
  { id: 48, word: "Armut", forbidden: ["Meyve", "Ağaç", "Sap", "Tatlı", "Sonbahar", "Yeşil", "Sulu"] },
  { id: 49, word: "Şeftali", forbidden: ["Meyve", "Tüylü", "Çekirdek", "Yaz", "Tatlı", "Ağaç", "Sulu"] },
  { id: 50, word: "Kiraz", forbidden: ["Meyve", "Kırmızı", "Sap", "Küçük", "Ağaç", "Tatlı", "Çekirdek"] },
  { id: 51, word: "Çay", forbidden: ["Bardak", "Sıcak", "Demlik", "Şeker", "Kahvaltı", "Yaprak", "Karadeniz"] },
  { id: 52, word: "Kahve", forbidden: ["Fincan", "Sıcak", "Kafein", "Çekirdek", "Sabah", "Köpük", "Telve"] },
  { id: 53, word: "Ayran", forbidden: ["Yoğurt", "Tuz", "Beyaz", "Soğuk", "Bardak", "Türk", "İçecek"] },
  { id: 54, word: "Meyve Suyu", forbidden: ["Portakal", "Sıkmak", "Kutu", "Vitamin", "İçecek", "Soğuk", "Bardak"] },
  { id: 55, word: "Gazoz", forbidden: ["Köpük", "Şişe", "Soğuk", "Tatlı", "İçecek", "Bardak", "Gaz"] },
  { id: 56, word: "Limonata", forbidden: ["Limon", "Ekşi", "Şeker", "Soğuk", "Yaz", "İçecek", "Bardak"] },
  { id: 57, word: "Kola", forbidden: ["Şişe", "Kutu", "Kahverengi", "Gazlı", "Soğuk", "İçecek", "Tatlı"] },
  { id: 58, word: "Bira", forbidden: ["Köpük", "Fıçı", "Şişe", "Alkol", "Soğuk", "Bardak", "Sarı"] },
  { id: 59, word: "Şalgam", forbidden: ["Kırmızı", "Ekşi", "Acı", "Adana", "İçecek", "Turp", "Bardak"] },
  { id: 60, word: "Maden Suyu", forbidden: ["Gazlı", "Soda", "Şişe", "Kabarcık", "Su", "Bardak", "İçecek"] },
  { id: 61, word: "Kedi", forbidden: ["Miyav", "Tüy", "Pati", "Evcil", "Köpek", "Kuyruk", "Kaplan"] },
  { id: 62, word: "Köpek", forbidden: ["Havlamak", "Kuyruk", "Evcil", "Kedi", "Kemik", "Pati", "Sadık"] },
  { id: 63, word: "Kuş", forbidden: ["Kanat", "Uçmak", "Tüy", "Gaga", "Yuva", "Ötmek", "Gökyüzü"] },
  { id: 64, word: "Balık", forbidden: ["Yüzmek", "Su", "Solungaç", "Pul", "Deniz", "Kılçık", "Akvaryum"] },
  { id: 65, word: "At", forbidden: ["Nal", "Yele", "Koşmak", "Eyer", "Çiftlik", "Kişnemek", "Binmek"] },
  { id: 66, word: "İnek", forbidden: ["Süt", "Çiftlik", "Boynuz", "Böğürmek", "Ot", "Buzağı", "Ahır"] },
  { id: 67, word: "Koyun", forbidden: ["Yün", "Çiftlik", "Kuzu", "Melemek", "Sürü", "Beyaz", "Ot"] },
  { id: 68, word: "Keçi", forbidden: ["Boynuz", "Çiftlik", "Sakal", "Süt", "Melemek", "Dağ", "Ot"] },
  { id: 69, word: "Tavuk", forbidden: ["Yumurta", "Kümes", "Gaga", "Horoz", "Tüy", "Civciv", "Kanat"] },
  { id: 70, word: "Horoz", forbidden: ["Kümes", "Ötmek", "İbik", "Tavuk", "Sabah", "Kanat", "Tüy"] },
  { id: 71, word: "Ördek", forbidden: ["Su", "Gaga", "Yüzmek", "Tüy", "Vak", "Göl", "Kuş"] },
  { id: 72, word: "Kaplumbağa", forbidden: ["Kabuk", "Yavaş", "Deniz", "Sürüngen", "Bacak", "Uzun Ömür", "Kum"] },
  { id: 73, word: "Tavşan", forbidden: ["Kulak", "Zıplamak", "Havuç", "Beyaz", "Yumuşak", "Hızlı", "Yuva"] },
  { id: 74, word: "Fare", forbidden: ["Küçük", "Kuyruk", "Peynir", "Kemirmek", "Kedi", "Delik", "Gri"] },
  { id: 75, word: "Yılan", forbidden: ["Sürünmek", "Zehir", "Uzun", "Dil", "Kabuk", "Sürüngen", "Korku"] },
  { id: 76, word: "Ayı", forbidden: ["Büyük", "Orman", "Pati", "Bal", "Kürk", "Kış Uykusu", "Vahşi"] },
  { id: 77, word: "Kurt", forbidden: ["Orman", "Vahşi", "Uluma", "Sürü", "Diş", "Gri", "Avcı"] },
  { id: 78, word: "Tilki", forbidden: ["Kurnaz", "Kuyruk", "Turuncu", "Orman", "Tavuk", "Vahşi", "Avcı"] },
  { id: 79, word: "Maymun", forbidden: ["Muz", "Ağaç", "Kuyruk", "Orman", "Zeki", "Sıçramak", "Kürk"] },
  { id: 80, word: "Zürafa", forbidden: ["Uzun Boyun", "Afrika", "Benekli", "Yaprak", "Uzun", "Savana", "Büyük"] },
  { id: 81, word: "Timsah", forbidden: ["Nehir", "Diş", "Uzun", "Tehlikeli", "Sürüngen", "Çene", "Avcı"] },
  { id: 82, word: "Penguen", forbidden: ["Kutup", "Buz", "Siyah Beyaz", "Kanat", "Yüzmek", "Balık", "Soğuk"] },
  { id: 83, word: "Karınca", forbidden: ["Küçük", "Koloni", "Yuva", "Çalışkan", "Böcek", "Sırt", "Yiyecek"] },
  { id: 84, word: "Arı", forbidden: ["Bal", "Kovan", "Sokmak", "Uçmak", "Çiçek", "Sarı Siyah", "Petek"] },
  { id: 85, word: "Örümcek", forbidden: ["Ağ", "Sekiz Bacak", "Böcek", "Zehir", "Köşe", "Avlamak", "Tuzak"] },
  { id: 86, word: "Doktor", forbidden: ["Hastane", "Muayene", "Reçete", "İlaç", "Beyaz Önlük", "Hasta", "Ameliyat"] },
  { id: 87, word: "Öğretmen", forbidden: ["Okul", "Ders", "Tahta", "Öğrenci", "Sınıf", "Kitap", "Sınav"] },
  { id: 88, word: "Polis", forbidden: ["Üniforma", "Suç", "Kanun", "Düdük", "Kelepçe", "Devriye", "Araba"] },
  { id: 89, word: "İtfaiyeci", forbidden: ["Yangın", "Hortum", "Kamyon", "Su", "Miğfer", "Alev", "Kurtarmak"] },
  { id: 90, word: "Mühendis", forbidden: ["İnşaat", "Proje", "Hesap", "Çizim", "Makine", "Yapı", "Plan"] },
  { id: 91, word: "Avukat", forbidden: ["Mahkeme", "Kanun", "Dava", "Savunma", "Hakim", "Adalet", "Ceza"] },
  { id: 92, word: "Hemşire", forbidden: ["Hastane", "İğne", "Doktor", "Beyaz", "Hasta", "Bakım", "Serum"] },
  { id: 93, word: "Aşçı", forbidden: ["Mutfak", "Yemek", "Tarif", "Tencere", "Restoran", "Bıçak", "Şapka"] },
  { id: 94, word: "Terzi", forbidden: ["Dikiş", "Kumaş", "İğne", "Makas", "Kıyafet", "Ölçü", "Elbise"] },
  { id: 95, word: "Berber", forbidden: ["Saç", "Makas", "Tıraş", "Ayna", "Salon", "Sakal", "Fön"] },
  { id: 96, word: "Çiftçi", forbidden: ["Toprak", "Tarla", "Ekin", "Traktör", "Hasat", "Tohum", "Köy"] },
  { id: 97, word: "Şoför", forbidden: ["Araba", "Direksiyon", "Yol", "Ehliyet", "Yolcu", "Trafik", "Otobüs"] },
  { id: 98, word: "Pilot", forbidden: ["Uçak", "Havaalanı", "Gökyüzü", "Kokpit", "Uçmak", "Bilet", "Yolcu"] },
  { id: 99, word: "Kaptan", forbidden: ["Gemi", "Deniz", "Dümen", "Liman", "Yolcu", "Rota", "Güverte"] },
  { id: 100, word: "Ressam", forbidden: ["Tuval", "Fırça", "Boya", "Sanat", "Resim", "Renk", "Sergi"] },
  { id: 101, word: "Yazar", forbidden: ["Kitap", "Kalem", "Roman", "Sayfa", "Hikaye", "Yayın", "Okur"] },
  { id: 102, word: "Gazeteci", forbidden: ["Haber", "Röportaj", "Kalem", "Kamera", "Basın", "Manşet", "Dergi"] },
  { id: 103, word: "Mimar", forbidden: ["Bina", "Çizim", "Plan", "İnşaat", "Tasarım", "Proje", "Yapı"] },
  { id: 104, word: "Eczacı", forbidden: ["İlaç", "Reçete", "Eczane", "Doktor", "Vitamin", "Raf", "Kutu"] },
  { id: 105, word: "Veteriner", forbidden: ["Hayvan", "Muayene", "Aşı", "Klinik", "Tedavi", "İğne", "Bakım"] },
  { id: 106, word: "Garson", forbidden: ["Restoran", "Sipariş", "Menü", "Masa", "Tepsi", "Müşteri", "Hesap"] },
  { id: 107, word: "Kasap", forbidden: ["Et", "Bıçak", "Market", "Tezgah", "Kesmek", "Tartı", "Kırmızı Et"] },
  { id: 108, word: "Fırıncı", forbidden: ["Ekmek", "Un", "Fırın", "Hamur", "Somun", "Simit", "Pastane"] },
  { id: 109, word: "Elektrikçi", forbidden: ["Kablo", "Priz", "Sigorta", "Tamir", "Elektrik", "Tesisat", "Ampul"] },
  { id: 110, word: "Şef", forbidden: ["Mutfak", "Aşçı", "Tarif", "Restoran", "Yemek", "Pişirmek", "Ekip"] },
  { id: 111, word: "Güneş", forbidden: ["Işık", "Sıcak", "Gökyüzü", "Sarı", "Gündüz", "Isı", "Doğmak"] },
  { id: 112, word: "Ay", forbidden: ["Gece", "Yıldız", "Işık", "Gökyüzü", "Dünya", "Uzay", "Tutulma"] },
  { id: 113, word: "Yıldız", forbidden: ["Gece", "Gökyüzü", "Parlamak", "Işık", "Uzay", "Kayan", "Takımyıldız"] },
  { id: 114, word: "Bulut", forbidden: ["Gökyüzü", "Beyaz", "Yağmur", "Gri", "Hava", "Şekil", "Yüksek"] },
  { id: 115, word: "Yağmur", forbidden: ["Bulut", "Su", "Şemsiye", "Islak", "Gökkuşağı", "Damla", "Fırtına"] },
  { id: 116, word: "Kar", forbidden: ["Beyaz", "Soğuk", "Kış", "Kartopu", "Kayak", "Yağmak", "Buz"] },
  { id: 117, word: "Rüzgar", forbidden: ["Hava", "Esmek", "Fırtına", "Hızlı", "Yaprak", "Uçurtma", "Soğuk"] },
  { id: 118, word: "Fırtına", forbidden: ["Rüzgar", "Yağmur", "Şimşek", "Deniz", "Bulut", "Tehlikeli", "Hava"] },
  { id: 119, word: "Gökkuşağı", forbidden: ["Renk", "Yağmur", "Güneş", "Gökyüzü", "Yedi Renk", "Kavis", "Doğa"] },
  { id: 120, word: "Şimşek", forbidden: ["Gökyüzü", "Fırtına", "Işık", "Gürültü", "Yıldırım", "Bulut", "Hızlı"] },
  { id: 121, word: "Deniz", forbidden: ["Su", "Dalga", "Kum", "Tuz", "Balık", "Sahil", "Yüzmek"] },
  { id: 122, word: "Göl", forbidden: ["Su", "Kıyı", "Balık", "Durgun", "Doğa", "Kayık", "Yüzmek"] },
  { id: 123, word: "Nehir", forbidden: ["Su", "Akmak", "Köprü", "Kıyı", "Balık", "Uzun", "Doğa"] },
  { id: 124, word: "Dağ", forbidden: ["Yüksek", "Zirve", "Kar", "Tırmanmak", "Vadi", "Kaya", "Doğa"] },
  { id: 125, word: "Orman", forbidden: ["Ağaç", "Yeşil", "Hayvan", "Doğa", "Yaprak", "Patika", "Kuş"] },
  { id: 126, word: "Çöl", forbidden: ["Kum", "Kurak", "Deve", "Sıcak", "Vaha", "Susuz", "Geniş"] },
  { id: 127, word: "Ada", forbidden: ["Deniz", "Kıyı", "Etraf", "Tekne", "Küçük", "Su", "Turizm"] },
  { id: 128, word: "Vadi", forbidden: ["Dağ", "Çukur", "Nehir", "Yeşil", "Doğa", "Geniş", "Manzara"] },
  { id: 129, word: "Volkan", forbidden: ["Lav", "Patlama", "Dağ", "Kül", "Sıcak", "Krater", "Doğa"] },
  { id: 130, word: "Deprem", forbidden: ["Sarsıntı", "Yer", "Yıkım", "Fay", "Bina", "Tehlike", "Doğa"] },
  { id: 131, word: "Araba", forbidden: ["Tekerlek", "Motor", "Direksiyon", "Yol", "Sürmek", "Benzin", "Garaj"] },
  { id: 132, word: "Otobüs", forbidden: ["Yolcu", "Durak", "Şoför", "Bilet", "Koltuk", "Şehir", "Uzun"] },
  { id: 133, word: "Tren", forbidden: ["Ray", "İstasyon", "Vagon", "Yolcu", "Hızlı", "Bilet", "Uzun"] },
  { id: 134, word: "Uçak", forbidden: ["Kanat", "Pilot", "Havaalanı", "Uçmak", "Bilet", "Bulut", "Yolculuk"] },
  { id: 135, word: "Gemi", forbidden: ["Deniz", "Liman", "Kaptan", "Güverte", "Yolcu", "Dev", "Yüzmek"] },
  { id: 136, word: "Bisiklet", forbidden: ["Tekerlek", "Pedal", "Zincir", "Sürmek", "Yol", "Denge", "İki Tekerlek"] },
  { id: 137, word: "Motosiklet", forbidden: ["Tekerlek", "Motor", "Hız", "Kask", "Sürmek", "Yol", "İki Tekerlek"] },
  { id: 138, word: "Taksi", forbidden: ["Araba", "Şoför", "Sarı", "Yolcu", "Ücret", "Sayaç", "Durak"] },
  { id: 139, word: "Metro", forbidden: ["Yeraltı", "İstasyon", "Yolcu", "Hızlı", "Vagon", "Şehir", "Ray"] },
  { id: 140, word: "Tramvay", forbidden: ["Ray", "Şehir", "Yolcu", "Elektrik", "Durak", "Vagon", "Yavaş"] },
  { id: 141, word: "Kamyon", forbidden: ["Yük", "Büyük", "Şoför", "Taşımak", "Motor", "Yol", "Dorse"] },
  { id: 142, word: "Helikopter", forbidden: ["Pervane", "Uçmak", "Gökyüzü", "Pilot", "İniş", "Kurtarma", "Havalanmak"] },
  { id: 143, word: "Kayık", forbidden: ["Su", "Kürek", "Göl", "Balıkçı", "Küçük", "Yüzmek", "Tekne"] },
  { id: 144, word: "Teleferik", forbidden: ["Dağ", "Kabin", "Havada", "Tel", "Yüksek", "Kayak", "Yolcu"] },
  { id: 145, word: "Gömlek", forbidden: ["Kıyafet", "Düğme", "Yaka", "Kol", "Kumaş", "Giyim", "Ütü"] },
  { id: 146, word: "Pantolon", forbidden: ["Kıyafet", "Bacak", "Kemer", "Cep", "Kumaş", "Giyim", "Fermuar"] },
  { id: 147, word: "Elbise", forbidden: ["Kıyafet", "Kadın", "Kumaş", "Etek", "Giyim", "Renk", "Düğün"] },
  { id: 148, word: "Etek", forbidden: ["Kıyafet", "Kadın", "Kumaş", "Bel", "Giyim", "Kısa", "Uzun"] },
  { id: 149, word: "Ceket", forbidden: ["Kıyafet", "Kol", "Düğme", "Kumaş", "Kış", "Giyim", "Cep"] },
  { id: 150, word: "Mont", forbidden: ["Kıyafet", "Kış", "Kalın", "Fermuar", "Soğuk", "Kapüşon", "Giyim"] },
  { id: 151, word: "Ayakkabı", forbidden: ["Ayak", "Bağcık", "Taban", "Deri", "Giyim", "Numara", "Yürümek"] },
  { id: 152, word: "Çorap", forbidden: ["Ayak", "Kumaş", "Çift", "Giyim", "Yün", "Ayakkabı", "Renkli"] },
  { id: 153, word: "Şapka", forbidden: ["Baş", "Güneş", "Kış", "Giyim", "Kenar", "Örtmek", "Moda"] },
  { id: 154, word: "Eldiven", forbidden: ["El", "Parmak", "Kış", "Soğuk", "Giyim", "Deri", "Sıcak"] },
  { id: 155, word: "Atkı", forbidden: ["Boyun", "Kış", "Yün", "Soğuk", "Giyim", "Uzun", "Örgü"] },
  { id: 156, word: "Kemer", forbidden: ["Bel", "Pantolon", "Deri", "Toka", "Giyim", "Uzun", "Tutmak"] },
  { id: 157, word: "Kravat", forbidden: ["Boyun", "Yaka", "Takım Elbise", "Düğüm", "Erkek", "Giyim", "Renkli"] },
  { id: 158, word: "Çanta", forbidden: ["Taşımak", "Sap", "Okul", "Kadın", "El", "Fermuar", "Cep"] },
  { id: 159, word: "Gözlük", forbidden: ["Göz", "Cam", "Görmek", "Çerçeve", "Güneş", "Numara", "Takmak"] },
  { id: 160, word: "Göz", forbidden: ["Görmek", "Kirpik", "Kaş", "Renk", "Yüz", "Bakmak", "Yaş"] },
  { id: 161, word: "Kulak", forbidden: ["Duymak", "Ses", "Yüz", "Küpe", "İşitmek", "Baş", "Delik"] },
  { id: 162, word: "Burun", forbidden: ["Koklamak", "Yüz", "Nefes", "Delik", "Koku", "Kırmızı", "Solumak"] },
  { id: 163, word: "Ağız", forbidden: ["Diş", "Dudak", "Yemek", "Konuşmak", "Dil", "Yüz", "Gülmek"] },
  { id: 164, word: "El", forbidden: ["Parmak", "Tutmak", "Avuç", "Kol", "Beş", "Tırnak", "Dokunmak"] },
  { id: 165, word: "Ayak", forbidden: ["Parmak", "Yürümek", "Taban", "Bacak", "Ayakkabı", "Beş", "Topuk"] },
  { id: 166, word: "Kalp", forbidden: ["Kan", "Atmak", "Göğüs", "Sevgi", "Organ", "Nabız", "Damar"] },
  { id: 167, word: "Saç", forbidden: ["Baş", "Uzun", "Tarak", "Renk", "Kesmek", "Şampuan", "Tel"] },
  { id: 168, word: "Diş", forbidden: ["Ağız", "Beyaz", "Fırça", "Çürük", "Çene", "Gülmek", "Doktor"] },
  { id: 169, word: "Parmak", forbidden: ["El", "Beş", "Tırnak", "Yüzük", "Ayak", "Uzun", "Dokunmak"] },
  { id: 170, word: "Kol", forbidden: ["El", "Omuz", "Uzun", "Kısa", "Kırık", "Vücut", "Bilek"] },
  { id: 171, word: "Bacak", forbidden: ["Ayak", "Diz", "Uzun", "Yürümek", "Kısa", "Vücut", "Koşmak"] },
  { id: 172, word: "Omuz", forbidden: ["Kol", "Sırt", "Çanta", "Vücut", "Ağrı", "Taşımak", "Geniş"] },
  { id: 173, word: "Sırt", forbidden: ["Omuz", "Bel", "Vücut", "Çanta", "Ağrı", "Düz", "Taşımak"] },
  { id: 174, word: "Dil (organ)", forbidden: ["Ağız", "Tat", "Konuşmak", "Kırmızı", "Yemek", "Uzun", "Damak"] },
  { id: 175, word: "Anne", forbidden: ["Aile", "Sevgi", "Çocuk", "Baba", "Ev", "Şefkat", "Kadın"] },
  { id: 176, word: "Baba", forbidden: ["Aile", "Çocuk", "Anne", "Ev", "Erkek", "Koruma", "Şefkat"] },
  { id: 177, word: "Kardeş", forbidden: ["Aile", "Abla", "Abi", "Ev", "Sevgi", "Aynı Aile", "Küçük"] },
  { id: 178, word: "Dede", forbidden: ["Aile", "Yaşlı", "Torun", "Anlatmak", "Sevgi", "Nine", "Bilge"] },
  { id: 179, word: "Nine", forbidden: ["Aile", "Yaşlı", "Torun", "Örgü", "Sevgi", "Dede", "Şefkat"] },
  { id: 180, word: "Teyze", forbidden: ["Aile", "Anne", "Kardeş", "Ziyaret", "Sevgi", "Kadın", "Akraba"] },
  { id: 181, word: "Dayı", forbidden: ["Aile", "Anne", "Kardeş", "Ziyaret", "Sevgi", "Erkek", "Akraba"] },
  { id: 182, word: "Amca", forbidden: ["Aile", "Baba", "Kardeş", "Ziyaret", "Sevgi", "Erkek", "Akraba"] },
  { id: 183, word: "Hala", forbidden: ["Aile", "Baba", "Kardeş", "Ziyaret", "Sevgi", "Kadın", "Akraba"] },
  { id: 184, word: "Arkadaş", forbidden: ["Dost", "Sevgi", "Oyun", "Okul", "Güven", "Sohbet", "Yakın"] },
  { id: 185, word: "Komşu", forbidden: ["Ev", "Yakın", "Sokak", "Ziyaret", "Bina", "Selam", "Ödünç"] },
  { id: 186, word: "Bebek", forbidden: ["Küçük", "Ağlamak", "Anne", "Beşik", "Biberon", "Emeklemek", "Masum"] },
  { id: 187, word: "Gelin", forbidden: ["Düğün", "Beyaz", "Damat", "Nikah", "Peçe", "Tören", "Elbise"] },
  { id: 188, word: "Damat", forbidden: ["Düğün", "Gelin", "Nikah", "Takım Elbise", "Tören", "Erkek", "Yüzük"] },
  { id: 189, word: "Futbol", forbidden: ["Top", "Kale", "Gol", "Saha", "Hakem", "Forma", "Stadyum"] },
  { id: 190, word: "Basketbol", forbidden: ["Pota", "Top", "Saha", "Smaç", "Faul", "Sıçramak", "Potaya Atmak"] },
  { id: 191, word: "Voleybol", forbidden: ["Top", "File", "Saha", "Smaç", "Takım", "Servis", "Blok"] },
  { id: 192, word: "Yüzme", forbidden: ["Havuz", "Su", "Mayo", "Kulaç", "Deniz", "Kurbağalama", "Şampiyona"] },
  { id: 193, word: "Koşu", forbidden: ["Hızlı", "Pist", "Nefes", "Yarış", "Ayakkabı", "Maraton", "Antrenman"] },
  { id: 194, word: "Tenis", forbidden: ["Raket", "Top", "Kort", "File", "Servis", "Set", "Maç"] },
  { id: 195, word: "Güreş", forbidden: ["Mat", "Ter", "Kuvvet", "Rakip", "Minder", "Yağ", "Turnuva"] },
  { id: 196, word: "Boks", forbidden: ["Yumruk", "Eldiven", "Ring", "Rakip", "Nakavt", "Antrenör", "Maç"] },
  { id: 197, word: "Satranç", forbidden: ["Tahta", "Taş", "Şah", "Vezir", "Strateji", "Rakip", "Hamle"] },
  { id: 198, word: "Kayak", forbidden: ["Kar", "Dağ", "Kış", "Kayma", "Ayakkabı", "Pist", "Hız"] },
  { id: 199, word: "Dalış", forbidden: ["Su", "Deniz", "Tüp", "Balık", "Derin", "Maske", "Nefes"] },
  { id: 200, word: "Atletizm", forbidden: ["Koşu", "Pist", "Yarış", "Antrenman", "Sporcu", "Stadyum", "Madalya"] },
  { id: 201, word: "Jimnastik", forbidden: ["Esneklik", "Minder", "Denge", "Halka", "Salon", "Antrenör", "Yarışma"] },
  { id: 202, word: "Bovling", forbidden: ["Top", "Pin", "Salon", "Devirmek", "Skor", "Ayakkabı", "Yarışma"] },
  { id: 203, word: "Mutlu", forbidden: ["Gülmek", "Sevinç", "Neşe", "Duygu", "Keyif", "Pozitif", "Kahkaha"] },
  { id: 204, word: "Üzgün", forbidden: ["Ağlamak", "Keder", "Duygu", "Hüzün", "Gözyaşı", "Kötü", "Yalnız"] },
  { id: 205, word: "Kızgın", forbidden: ["Sinirli", "Öfke", "Duygu", "Bağırmak", "Kırmızı", "Gerginlik", "Kavga"] },
  { id: 206, word: "Korkmuş", forbidden: ["Korku", "Ürkmek", "Titremek", "Duygu", "Karanlık", "Kabus", "Kaçmak"] },
  { id: 207, word: "Şaşırmış", forbidden: ["Şaşkın", "Duygu", "Beklenmedik", "Ağız Açık", "Hayret", "Gözler", "Sürpriz"] },
  { id: 208, word: "Yorgun", forbidden: ["Uyku", "Bitkin", "Dinlenmek", "Enerji", "Halsiz", "Uyumak", "Güç"] },
  { id: 209, word: "Heyecanlı", forbidden: ["Coşku", "Kalp Atışı", "Bekleyiş", "Duygu", "Titreme", "Sürpriz", "Enerji"] },
  { id: 210, word: "Sakin", forbidden: ["Huzur", "Dingin", "Rahat", "Duygu", "Yavaş", "Dinlenmek", "Sessiz"] },
  { id: 211, word: "Meraklı", forbidden: ["Soru", "İlgi", "Öğrenmek", "Duygu", "Araştırmak", "Keşif", "Bilgi"] },
  { id: 212, word: "Cesur", forbidden: ["Korkusuz", "Kahraman", "Güç", "Risk", "Duygu", "Yiğit", "Mücadele"] },
  { id: 213, word: "Koşmak", forbidden: ["Hızlı", "Ayak", "Nefes", "Yarış", "Spor", "Yorulmak", "Adım"] },
  { id: 214, word: "Yüzmek", forbidden: ["Su", "Havuz", "Deniz", "Kulaç", "Mayo", "Boğulmak", "Kurbağalama"] },
  { id: 215, word: "Uçmak", forbidden: ["Kanat", "Gökyüzü", "Kuş", "Uçak", "Yükselmek", "Havada", "Süzülmek"] },
  { id: 216, word: "Uyumak", forbidden: ["Yatak", "Göz", "Rüya", "Yorgan", "Gece", "Yastık", "Dinlenmek"] },
  { id: 217, word: "Gülmek", forbidden: ["Kahkaha", "Mutluluk", "Ağız", "Diş", "Neşe", "Şaka", "Yüz"] },
  { id: 218, word: "Ağlamak", forbidden: ["Gözyaşı", "Üzüntü", "Göz", "Hüzün", "Ses", "Duygu", "Mendil"] },
  { id: 219, word: "Dans Etmek", forbidden: ["Müzik", "Hareket", "Ayak", "Ritim", "Salon", "Eğlence", "Ayakkabı"] },
  { id: 220, word: "Şarkı Söylemek", forbidden: ["Ses", "Müzik", "Mikrofon", "Nota", "Melodi", "Sahne", "Söz"] },
  { id: 221, word: "Yemek Yemek", forbidden: ["Ağız", "Sofra", "Çatal", "Kaşık", "Tabak", "Aç", "Lezzet"] },
  { id: 222, word: "Resim Yapmak", forbidden: ["Fırça", "Boya", "Tuval", "Kağıt", "Renk", "Sanat", "Çizmek"] },
  { id: 223, word: "Kitap Okumak", forbidden: ["Sayfa", "Göz", "Kütüphane", "Roman", "Harf", "Öğrenmek", "Kelime"] },
  { id: 224, word: "Yazı Yazmak", forbidden: ["Kalem", "Kağıt", "El", "Harf", "Defter", "Mektup", "Kelime"] },
  { id: 225, word: "Konuşmak", forbidden: ["Ağız", "Ses", "Kelime", "Dil", "Sohbet", "Dinlemek", "İletişim"] },
  { id: 226, word: "Dinlemek", forbidden: ["Kulak", "Ses", "Müzik", "Sessizlik", "Kelime", "Konuşma", "Dikkat"] },
  { id: 227, word: "İzlemek", forbidden: ["Göz", "Ekran", "Film", "Dizi", "Televizyon", "Dikkat", "Sahne"] },
  { id: 228, word: "Oynamak", forbidden: ["Oyun", "Çocuk", "Eğlence", "Top", "Arkadaş", "Kural", "Zaman"] },
  { id: 229, word: "Çalışmak", forbidden: ["İş", "Ofis", "Emek", "Zaman", "Görev", "Yorgunluk", "Maaş"] },
  { id: 230, word: "Dinlenmek", forbidden: ["Yorgun", "Uyku", "Rahat", "Kanepe", "Tatil", "Huzur", "Sessizlik"] },
  { id: 231, word: "Yürümek", forbidden: ["Ayak", "Adım", "Yol", "Hız", "Bacak", "Ayakkabı", "Gezmek"] },
  { id: 232, word: "Zıplamak", forbidden: ["Ayak", "Yukarı", "Sıçramak", "Enerji", "Hareket", "Havaya", "Yer"] },
  { id: 233, word: "Bilgisayar", forbidden: ["Klavye", "Fare", "Ekran", "İnternet", "Yazılım", "Teknoloji", "Dizüstü"] },
  { id: 234, word: "Telefon", forbidden: ["Arama", "Mesaj", "Ekran", "Uygulama", "Şarj", "Akıllı", "Kamera"] },
  { id: 235, word: "Televizyon", forbidden: ["Ekran", "Kumanda", "Kanal", "Dizi", "Netflix", "İzlemek", "Uzaktan"] },
  { id: 236, word: "Kamera", forbidden: ["Fotoğraf", "Lens", "Çekmek", "Flaş", "Görüntü", "Objektif", "Video"] },
  { id: 237, word: "Kulaklık", forbidden: ["Müzik", "Ses", "Kulak", "Kablo", "Telefon", "Dinlemek", "Kafa"] },
  { id: 238, word: "Şarj Aleti", forbidden: ["Kablo", "Pil", "Priz", "Telefon", "Elektrik", "Doldurmak", "Batarya"] },
  { id: 239, word: "Tablet", forbidden: ["Ekran", "Dokunmatik", "İnternet", "Uygulama", "Taşınabilir", "Şarj", "Teknoloji"] },
  { id: 240, word: "Yazıcı", forbidden: ["Kağıt", "Mürekkep", "Baskı", "Belge", "Ofis", "Tarama", "Toner"] },
  { id: 241, word: "Robot", forbidden: ["Makine", "Yapay Zeka", "Metal", "Gelecek", "Otomatik", "Devre", "Program"] },
  { id: 242, word: "İnternet", forbidden: ["Bağlantı", "Wifi", "Ağ", "Site", "Modem", "Ekran", "Veri"] },
  { id: 243, word: "Oyun Konsolu", forbidden: ["Kumanda", "Ekran", "Oyun", "Televizyon", "Disk", "Karakter", "Skor"] },
  { id: 244, word: "Hoparlör", forbidden: ["Ses", "Müzik", "Kablo", "Bluetooth", "Yüksek", "Bas", "Elektrik"] },
  { id: 245, word: "Drone", forbidden: ["Uçmak", "Kamera", "Uzaktan", "Pervane", "Gökyüzü", "Kumanda", "Video"] },
  { id: 246, word: "Kalem", forbidden: ["Yazmak", "Uç", "Silgi", "Kutu", "Kağıt", "Mürekkep", "Okul"] },
  { id: 247, word: "Silgi", forbidden: ["Kalem", "Hata", "Silmek", "Kağıt", "Okul", "Kauçuk", "Küçük"] },
  { id: 248, word: "Defter", forbidden: ["Sayfa", "Yazmak", "Kalem", "Okul", "Kapak", "Ders", "Çizgili"] },
  { id: 249, word: "Okul Çantası", forbidden: ["Sırt", "Fermuar", "Kitap", "Defter", "Taşımak", "Okul", "Sap"] },
  { id: 250, word: "Tahta", forbidden: ["Sınıf", "Yazmak", "Öğretmen", "Tebeşir", "Silmek", "Yeşil", "Ders"] },
  { id: 251, word: "Sınıf", forbidden: ["Okul", "Öğrenci", "Sıra", "Tahta", "Ders", "Öğretmen", "Duvar"] },
  { id: 252, word: "Öğrenci", forbidden: ["Okul", "Ders", "Sınav", "Öğretmen", "Sınıf", "Kitap", "Ödev"] },
  { id: 253, word: "Sınav", forbidden: ["Soru", "Kağıt", "Not", "Ders", "Okul", "Cevap", "Süre"] },
  { id: 254, word: "Ders", forbidden: ["Okul", "Öğretmen", "Konu", "Sınıf", "Kitap", "Öğrenmek", "Zil"] },
  { id: 255, word: "Cetvel", forbidden: ["Çizgi", "Ölçü", "Uzunluk", "Okul", "Düz", "Kenar", "Kalem"] },
  { id: 256, word: "Boya Kalemi", forbidden: ["Renk", "Resim", "Çizmek", "Kutu", "Okul", "Sanat", "Kağıt"] },
  { id: 257, word: "Harita", forbidden: ["Ülke", "Şehir", "Yol", "Coğrafya", "Kağıt", "Sınır", "Okul"] },
  { id: 258, word: "Küre", forbidden: ["Dünya", "Dönmek", "Coğrafya", "Kıta", "Okul", "Yuvarlak", "Harita"] },
  { id: 259, word: "Ev", forbidden: ["Oda", "Kapı", "Pencere", "Aile", "Çatı", "Bahçe", "Yaşamak"] },
  { id: 260, word: "Okul", forbidden: ["Öğretmen", "Öğrenci", "Ders", "Sınıf", "Sınav", "Tahta", "Zil"] },
  { id: 261, word: "Hastane", forbidden: ["Doktor", "Hasta", "Ameliyat", "Acil", "Yatak", "İlaç", "Hemşire"] },
  { id: 262, word: "Market", forbidden: ["Alışveriş", "Kasa", "Sepet", "Ürün", "Raf", "Fiyat", "Kasiyer"] },
  { id: 263, word: "Park", forbidden: ["Yeşil", "Bank", "Çocuk", "Salıncak", "Ağaç", "Yürüyüş", "Doğa"] },
  { id: 264, word: "Cami", forbidden: ["İbadet", "Minare", "Namaz", "Kubbe", "Din", "Ezan", "Avlu"] },
  { id: 265, word: "Kilise", forbidden: ["İbadet", "Din", "Çan", "Haç", "Papaz", "Tören", "Kutsal"] },
  { id: 266, word: "Müze", forbidden: ["Sergi", "Sanat", "Tarih", "Eser", "Gezmek", "Bilet", "Koleksiyon"] },
  { id: 267, word: "Sinema", forbidden: ["Film", "Perde", "Bilet", "Koltuk", "Karanlık", "Patlamış Mısır", "Salon"] },
  { id: 268, word: "Tiyatro", forbidden: ["Sahne", "Oyuncu", "Perde", "Bilet", "Salon", "Oyun", "Alkış"] },
  { id: 269, word: "Stadyum", forbidden: ["Futbol", "Tribün", "Saha", "Taraftar", "Maç", "Bilet", "Spor"] },
  { id: 270, word: "Otel", forbidden: ["Oda", "Tatil", "Resepsiyon", "Yatak", "Konaklama", "Anahtar", "Havlu"] },
  { id: 271, word: "Restoran", forbidden: ["Yemek", "Garson", "Menü", "Masa", "Sipariş", "Şef", "Hesap"] },
  { id: 272, word: "Kütüphane", forbidden: ["Kitap", "Sessizlik", "Raf", "Okumak", "Ödünç", "Masa", "Öğrenci"] },
  { id: 273, word: "Banka", forbidden: ["Para", "Hesap", "Kart", "Şube", "Kasa", "Kredi", "Müşteri"] },
  { id: 274, word: "Eczane", forbidden: ["İlaç", "Reçete", "Eczacı", "Doktor", "Vitamin", "Raf", "Sağlık"] },
  { id: 275, word: "Havalimanı", forbidden: ["Uçak", "Bilet", "Pasaport", "Bavul", "Yolcu", "Pist", "Gate"] },
  { id: 276, word: "İstasyon", forbidden: ["Tren", "Bilet", "Peron", "Yolcu", "Vagon", "Bekleme", "Ray"] },
  { id: 277, word: "Yaz", forbidden: ["Sıcak", "Tatil", "Deniz", "Güneş", "Mevsim", "Dondurma", "Plaj"] },
  { id: 278, word: "Kış", forbidden: ["Soğuk", "Kar", "Mevsim", "Mont", "Kayak", "Buz", "Ocak"] },
  { id: 279, word: "İlkbahar", forbidden: ["Çiçek", "Mevsim", "Yeşil", "Ilık", "Yağmur", "Uyanış", "Nisan"] },
  { id: 280, word: "Sonbahar", forbidden: ["Yaprak", "Mevsim", "Sarı", "Rüzgar", "Serin", "Ekim", "Düşmek"] },
  { id: 281, word: "Sabah", forbidden: ["Güneş", "Kahvaltı", "Uyanmak", "Erken", "Gün", "Kuş", "Işık"] },
  { id: 282, word: "Akşam", forbidden: ["Gün Batımı", "Yemek", "Karanlık", "Dinlenmek", "Gece", "Yorgun", "Ev"] },
  { id: 283, word: "Gece", forbidden: ["Karanlık", "Ay", "Yıldız", "Uyku", "Sessizlik", "Rüya", "Uyumak"] },
  { id: 284, word: "Gündüz", forbidden: ["Güneş", "Işık", "Aydınlık", "Çalışmak", "Gökyüzü", "Saat", "Aktif"] },
  { id: 285, word: "Hafta Sonu", forbidden: ["Tatil", "Dinlenmek", "Cumartesi", "Pazar", "Eğlence", "Uyku", "Gezmek"] },
  { id: 286, word: "Tatil", forbidden: ["Deniz", "Plaj", "Uçak", "Valiz", "Otel", "Güneş", "Dinlenmek"] },
  { id: 287, word: "Bayram", forbidden: ["Kutlama", "Aile", "Şeker", "Tören", "Ziyaret", "Tatil", "Sevinç"] },
  { id: 288, word: "Yılbaşı", forbidden: ["Kutlama", "Ocak", "Çam Ağacı", "Hediye", "Kar", "Gece", "Kutlamak"] },
  { id: 289, word: "Doğum Günü", forbidden: ["Pasta", "Mum", "Hediye", "Kutlama", "Yaş", "Balon", "Parti"] },
  { id: 290, word: "Kamp", forbidden: ["Çadır", "Ateş", "Doğa", "Orman", "Uyku Tulumu", "Gece", "Sırt Çantası"] },
  { id: 291, word: "Düğün", forbidden: ["Gelin", "Damat", "Nikah", "Tören", "Yüzük", "Beyaz Elbise", "Davet"] },
  { id: 292, word: "Korku Filmi", forbidden: ["Hayalet", "Karanlık", "Çığlık", "Canavar", "Kan", "Gerilim", "Zombi"] },
  { id: 293, word: "Komedi", forbidden: ["Gülmek", "Şaka", "Mizah", "Komik", "Eğlence", "Stand-up", "Kahkaha"] },
  { id: 294, word: "Balık Tutmak", forbidden: ["Olta", "Deniz", "Göl", "Yem", "Balık", "Tekne", "Bekleme"] },
  { id: 295, word: "Uzay", forbidden: ["Gezegen", "Yıldız", "Astronot", "Roket", "Ay", "Galaksi", "Boşluk"] },
  { id: 296, word: "Astronot", forbidden: ["Uzay", "Roket", "Gezegen", "Uçmak", "Ay", "NASA", "Skafandır"] },
  { id: 297, word: "Müzisyen", forbidden: ["Enstrüman", "Konser", "Şarkı", "Nota", "Sahne", "Albüm", "Ritim"] },
  { id: 298, word: "Gitar", forbidden: ["Tel", "Müzik", "Akor", "Enstrüman", "Çalmak", "Konser", "Amfi"] },
  { id: 299, word: "Piyano", forbidden: ["Tuş", "Müzik", "Nota", "Konser", "Siyah", "Beyaz", "Çalmak"] },
  { id: 300, word: "Davul", forbidden: ["Vurmak", "Ritim", "Müzik", "Enstrüman", "Baget", "Ses", "Konser"] },

  // Genel Kültür
  { id: 301, word: "Tarih", forbidden: ["Geçmiş", "Olay", "Tarih Öncesi", "Yüzyıl", "Kronoloji", "Dönem", "Belge"] },
  { id: 302, word: "Coğrafya", forbidden: ["Harita", "Dünya", "Kıta", "İklim", "Bölge", "Yeryüzü", "Ders"] },
  { id: 303, word: "Bayrak", forbidden: ["Ülke", "Renk", "Direk", "Sembol", "Vatan", "Ay Yıldız", "Tören"] },
  { id: 304, word: "Para", forbidden: ["Banknot", "Madeni", "Cüzdan", "Ekonomi", "Kazanmak", "Harcamak", "Banka"] },
  { id: 305, word: "Nüfus", forbidden: ["İnsan", "Sayım", "Şehir", "Ülke", "Yoğunluk", "Sayı", "Toplum"] },
  { id: 306, word: "Başkent", forbidden: ["Şehir", "Ülke", "Yönetim", "Merkez", "Devlet", "Meclis", "Ankara"] },
  { id: 307, word: "Cumhuriyet", forbidden: ["Devlet", "Yönetim", "Halk", "Meclis", "Bayram", "Atatürk", "Anayasa"] },
  { id: 308, word: "Anayasa", forbidden: ["Kanun", "Devlet", "Madde", "Hak", "Meclis", "Hukuk", "Yönetim"] },
  { id: 309, word: "Meclis", forbidden: ["Devlet", "Milletvekili", "Kanun", "Ankara", "Oylama", "Yönetim", "Bina"] },
  { id: 310, word: "Seçim", forbidden: ["Oy", "Sandık", "Aday", "Meclis", "Kampanya", "Sonuç", "Demokrasi"] },
  { id: 311, word: "Gazete", forbidden: ["Haber", "Kağıt", "Manşet", "Okumak", "Basın", "Sayfa", "Gündem"] },
  { id: 312, word: "Sözlük", forbidden: ["Kelime", "Anlam", "Kitap", "Dil", "TDK", "Sayfa", "Tanım"] },
  { id: 313, word: "Ansiklopedi", forbidden: ["Bilgi", "Kitap", "Madde", "Konu", "Ciltler", "Araştırma", "Kaynak"] },
  { id: 314, word: "Nobel Ödülü", forbidden: ["Bilim", "Başarı", "Ödül", "Dünya", "Yazar", "Barış", "Buluş"] },
  { id: 315, word: "Deniz Feneri", forbidden: ["Deniz", "Işık", "Gemi", "Kule", "Sahil", "Yön", "Kıyı"] },

  // Yazılım ve Teknoloji
  { id: 316, word: "S/4HANA", forbidden: ["SAP", "ERP", "Modül", "ECC", "Bulut", "Finans", "Lojistik"] },
  { id: 317, word: "Python", forbidden: ["Kod", "Yazılım", "Programlama", "Dil", "Script", "Kütüphane", "Django"] },
  { id: 318, word: "Siber Güvenlik", forbidden: ["Hacker", "Şifre", "Güvenlik Duvarı", "Virüs", "Veri", "Saldırı", "Şifreleme"] },
  { id: 319, word: "Loglama", forbidden: ["Kayıt", "Sistem", "Hata", "İzleme", "Log Dosyası", "Sunucu", "Analiz"] },
  { id: 320, word: "Sunucu", forbidden: ["Bilgisayar", "Veri", "Bulut", "Ağ", "Barındırma", "Merkez", "Erişim"] },
  { id: 321, word: "Lojistik Modülü", forbidden: ["SAP", "Depo", "Sevkiyat", "Stok", "Tedarik", "Sipariş", "Envanter"] },
  { id: 322, word: "İş Analisti", forbidden: ["Süreç", "Rapor", "Gereksinim", "Analiz", "Proje", "Danışman", "Toplantı"] },
  { id: 323, word: "Veritabanı", forbidden: ["Tablo", "Sorgu", "Kayıt", "SQL", "Sunucu", "Veri", "İlişkisel"] },
  { id: 324, word: "Bulut Bilişim", forbidden: ["Sunucu", "Veri", "Depolama", "İnternet", "Uzak", "Erişim", "Servis"] },
  { id: 325, word: "API", forbidden: ["Entegrasyon", "İstek", "Yanıt", "Yazılım", "Bağlantı", "Servis", "Anahtar"] },
  { id: 326, word: "Algoritma", forbidden: ["Kod", "Adım", "Mantık", "Çözüm", "Yazılım", "Sıralama", "Hesaplama"] },
  { id: 327, word: "Yazılım Testi", forbidden: ["Hata", "Kod", "Kontrol", "Kalite", "Senaryo", "Bug", "Onay"] },
  { id: 328, word: "Entegrasyon", forbidden: ["Sistem", "Bağlantı", "API", "Veri", "Modül", "Uyum", "Süreç"] },
  { id: 329, word: "Kullanıcı Arayüzü", forbidden: ["Ekran", "Tasarım", "Buton", "Menü", "Deneyim", "Ayar", "Görsel"] },
  { id: 330, word: "Versiyon Kontrolü", forbidden: ["Kod", "Git", "Değişiklik", "Geçmiş", "Depo", "Commit", "Yazılım"] },

  // Komedi ve Stand-up
  { id: 331, word: "Stand-up", forbidden: ["Komedyen", "Sahne", "Mikrofon", "Şaka", "Salon", "Gülmek", "Performans"] },
  { id: 332, word: "Komedyen", forbidden: ["Şaka", "Sahne", "Gülmek", "Mikrofon", "Stand-up", "Espri", "İzleyici"] },
  { id: 333, word: "Sahne", forbidden: ["Tiyatro", "Işık", "Perde", "Oyuncu", "Performans", "Salon", "Gösteri"] },
  { id: 334, word: "Mikrofon", forbidden: ["Ses", "Sahne", "Konuşmak", "Şarkı", "El", "Konser", "Sunucu"] },
  { id: 335, word: "Espri", forbidden: ["Şaka", "Gülmek", "Komik", "Mizah", "Kahkaha", "Sohbet", "Anlatmak"] },
  { id: 336, word: "Şaka", forbidden: ["Espri", "Gülmek", "Komik", "Mizah", "Kahkaha", "Oyun", "Şakacı"] },
  { id: 337, word: "Kahkaha", forbidden: ["Gülmek", "Neşe", "Mutluluk", "Şaka", "Ses", "Espri", "Yüz"] },
  { id: 338, word: "Taklit", forbidden: ["Yapmak", "Ses", "Kişi", "Benzetmek", "Komik", "Sahne", "Ünlü"] },
  { id: 339, word: "Doğaçlama", forbidden: ["Anlık", "Sahne", "Tiyatro", "Yaratıcılık", "Oyunculuk", "Plansız", "Grup"] },
  { id: 340, word: "Skeç", forbidden: ["Sahne", "Kısa", "Oyun", "Komedi", "Grup", "Senaryo", "Gösteri"] },
  { id: 341, word: "Parodi", forbidden: ["Taklit", "Komedi", "Esinlenmek", "Şarkı", "Film", "Mizah", "Benzetme"] },
  { id: 342, word: "Kostüm", forbidden: ["Kıyafet", "Sahne", "Karakter", "Giyinmek", "Parti", "Tiyatro", "Maske"] },
  { id: 343, word: "Alkış", forbidden: ["El Çırpmak", "Sahne", "Tebrik", "Seyirci", "Performans", "Ses", "Salon"] },
  { id: 344, word: "Bilet", forbidden: ["Sinema", "Konser", "Sahne", "Fiyat", "Giriş", "Etkinlik", "Koltuk"] },
  { id: 345, word: "İzleyici", forbidden: ["Seyirci", "Sahne", "Salon", "Alkış", "Koltuk", "Gösteri", "Bilet"] },

  // Sokak Ağzı / Günlük Yaşam
  { id: 346, word: "Kanka", forbidden: ["Arkadaş", "Dost", "Selam", "Yakın", "Laf", "Muhabbet", "Abi"] },
  { id: 347, word: "Muhabbet", forbidden: ["Sohbet", "Konuşmak", "Laf", "Arkadaş", "Kahve", "Gevezelik", "Dertleşmek"] },
  { id: 348, word: "Fenomen", forbidden: ["Ünlü", "Sosyal Medya", "Takipçi", "Influencer", "Video", "Popüler", "Paylaşım"] },
  { id: 349, word: "Trend", forbidden: ["Moda", "Popüler", "Sosyal Medya", "Akım", "Gündem", "Yaygın", "Viral"] },
  { id: 350, word: "Viral", forbidden: ["Video", "Paylaşım", "Sosyal Medya", "Yayılmak", "Popüler", "İnternet", "Trend"] },
  { id: 351, word: "Efsane", forbidden: ["Harika", "İnanılmaz", "Muhteşem", "Abartı", "Söylenti", "Ünlü", "Destan"] },
  { id: 352, word: "Takılmak", forbidden: ["Gezmek", "Arkadaş", "Vakit Geçirmek", "Sokak", "Buluşmak", "Eğlenmek", "Sohbet"] },
  { id: 353, word: "Sallamak", forbidden: ["Uydurmak", "Yalan", "Cevap", "Tahmin", "Bilmemek", "Gevelemek", "Rastgele"] },
  { id: 354, word: "Kafa Dağıtmak", forbidden: ["Eğlenmek", "Dinlenmek", "Stres", "Rahatlamak", "Gezmek", "Parti", "Müzik"] },
  { id: 355, word: "Trip Atmak", forbidden: ["Havalı", "Kibirli", "Poz", "Gösteriş", "Tavır", "Ukala", "Caka"] },
  { id: 356, word: "Kıyak", forbidden: ["İyilik", "Yardım", "Jest", "Dostluk", "Fedakarlık", "Sürpriz", "Cömert"] },
  { id: 357, word: "Çaktırmadan", forbidden: ["Gizlice", "Sessizce", "Farkettirmeden", "Sinsi", "Gizli", "Habersiz", "Sır"] },
  { id: 358, word: "Moral Bozmak", forbidden: ["Üzmek", "Kötü Haber", "Hayal Kırıklığı", "Keyifsiz", "Motivasyon", "Düşkırıklığı", "Umutsuz"] },
  { id: 359, word: "Kafayı Yemek", forbidden: ["Çıldırmak", "Sinirlenmek", "Bunalmak", "Stres", "Deli", "Bitmek", "Dayanamamak"] },
  { id: 360, word: "Havalı", forbidden: ["Şık", "Stil", "Etkileyici", "Trend", "Caka", "Marka", "Gösteriş"] },
];

// Kelime kategorileri — id aralıklarına göre atanır (kategori seçim ekranı için).
window.WORD_CATEGORIES = [
  { key: "ev-esyalari", label: "Ev Eşyaları", from: 1, to: 25 },
  { key: "yiyecek", label: "Yiyecek", from: 26, to: 50 },
  { key: "icecek", label: "İçecekler", from: 51, to: 60 },
  { key: "hayvanlar", label: "Hayvanlar", from: 61, to: 85 },
  { key: "meslekler", label: "Meslekler", from: 86, to: 110 },
  { key: "doga", label: "Doğa", from: 111, to: 130 },
  { key: "ulasim", label: "Ulaşım", from: 131, to: 144 },
  { key: "giyim", label: "Giyim", from: 145, to: 159 },
  { key: "vucut", label: "Vücut", from: 160, to: 174 },
  { key: "aile", label: "Aile", from: 175, to: 188 },
  { key: "spor", label: "Spor", from: 189, to: 202 },
  { key: "duygular", label: "Duygular", from: 203, to: 212 },
  { key: "eylemler", label: "Eylemler", from: 213, to: 232 },
  { key: "teknoloji", label: "Teknoloji", from: 233, to: 245 },
  { key: "okul", label: "Okul", from: 246, to: 258 },
  { key: "mekanlar", label: "Mekanlar", from: 259, to: 276 },
  { key: "zaman-mevsim", label: "Zaman & Mevsim", from: 277, to: 288 },
  { key: "eglence-diger", label: "Eğlence & Diğer", from: 289, to: 300 },
  { key: "genel-kultur", label: "Genel Kültür", from: 301, to: 315, accent: "#B8860B" },
  { key: "yazilim-teknoloji", label: "Yazılım & Teknoloji", from: 316, to: 330, accent: "#2196F3" },
  { key: "komedi-standup", label: "Komedi & Stand-up", from: 331, to: 345, accent: "#B565D9" },
  { key: "sokak-agzi", label: "Sokak Ağzı", from: 346, to: 360, accent: "#1F8A70" },
];

function categoryForId(id) {
  const found = window.WORD_CATEGORIES.find((c) => id >= c.from && id <= c.to);
  return found ? found.key : "diger";
}

window.WORDS_POOL.forEach((w) => {
  w.category = categoryForId(w.id);
});
